WIP: startup

diff --git a/tests/integ/Makefile b/tests/integ/Makefile
--- a/tests/integ/Makefile
+++ b/tests/integ/Makefile
@@ -3,16 +3,36 @@
 ################################################################################
 
 LATEST_TAG = $(shell bin/dockertags alpacamarkets/marketstore | tail -1)
+IMAGE_NAME = alpacamarkets/marketstore:${LATEST_TAG}
 
 # Utils
 ################################################################################
 
-connect:
-	curl -s --data-binary '{"jsonrpc":"2.0", "method":"DataService.ListSymbols", "id":1, "params": {"parameters": {}}}' -H 'Content-Type: application/json' http://localhost:5993/rpc
+connect: run
+	@curl -s --data-binary '{"jsonrpc":"2.0", "method":"DataService.ListSymbols", "id":1, "params": {"parameters": {}}}' -H 'Content-Type: application/json' http://localhost:5993/rpc ; if [ $$? -ne 0 ]; then echo "Failed"; else echo "Passed"; fi
+
 
 init:
-	if [ ! -d data ]; then mkdir data; else rm -rf data && mkdir data; fi
+	@if [ ! -d data ]; then $(MAKE) get_data; fi
+
+run: init
+	@if [ $(shell bin/check_running integ_test) -eq 0 ]; then $(MAKE) startup; fi
+
+get_data:
+	@mkdir data
 	wget https://s3.amazonaws.com/dev.alpaca.markets/gobroker/mktsdb.tar.gz -O /tmp/mktsdb.tgz && tar -C data -xzf /tmp/mktsdb.tgz && rm /tmp/mktsdb.tgz
+
+startup:
+	docker run --name integ_test -d -p 5993:5993 -v $(CURDIR):/project -w /project $(IMAGE_NAME) \
+		start --config /project/bin/mkts.yml
+	sleep 2
+
+stop:
+	docker stop integ_test
+	docker rm integ_test
+
+clean: stop
+	rm -rf data
 
 # Tests
 ################################################################################
